name: Test and publish
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test-project:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4.1.1

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: '8'
      
      - name: Cache dependencies
        uses: actions/cache@v4.0.0
        with:
          path: ~/.nuget
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore

      - name: Test
        run: dotnet test --no-restore --verbosity minimal

      - name: Print job complete
        run: echo "Test job complete time $(date)!"

  publish-project:
    runs-on: ubuntu-latest
    needs: test-project
    steps:  

      - name: Publish job start
        run: echo "Publish job start time $(date)!"

      - name: Check out code
        uses: actions/checkout@v4.1.1

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: '8'

      - name: Cache dependencies
        uses: actions/cache@v4.0.0
        with:
          path: ~/.nuget
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}

      - name: Install dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Create publish files
        run: dotnet publish --configuration Release -o ./publish

      - name: Deploy to Azure
        uses: Azure/webapps-deploy@v3.0.0
        with: 
          app-name: "github-actions-test-albin-123"
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE  }}
          package: './publish'

  create-issue:
    runs-on: ubuntu-latest
    needs: test-project
    if: failure()
    steps:
      - name: Print job started
        run: |
              echo "Test failed. . . "
              echo "Creating issue."