name: Test and publish
on: 
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test-project:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4.1.1

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: '8.0'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}

      - name: Install dependencies
        run: dotnet restore

      - name: Print job complete
        run: echo "Test job complete $(date)!" # Printa ut datum + klockslag
  publish-project:
    runs-on: ubuntu-latest
    needs: test-project
    steps:
      - name: Print job started
        run: echo "Publish job started $(date)!"

      - name: Check out code
        uses: actions/checkout@v4.1.1

      - name: Setup .NET
        uses: actions/setup-dotnet@v4.0.0
        with:
          dotnet-version: '8.0'

      - name: Cache dependencies
        uses: actions/cache@v3
        with:
          path: ~/.nuget/packages
          key: ${{ runner.os }}-nuget-${{ hashFiles('**/packages.lock.json') }}

      - name: Install dependencies
        run: dotnet restore